//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisWebServiceTest.HisWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HisWebService.ChisWebServiceSoap")]
    public interface ChisWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPayType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryPayType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCardAddPosit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateCardAddPosit(string CardNo, string PatientName, string Sex, string Birthday, string IDCardNo, string Nation, string Address, string Tel, string FlowNo, string Pwd, string Amt, string PayMode, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDeposit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddDeposit(string PatientID, string Amt, string PayMode, string BankNo, string FlowNo, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPatientID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryPatientID(string CardNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryBalanceRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryBalanceRecord(string PatientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryFeeDetailRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryFeeDetailRecord(string PatientID, string BeginDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryPatientInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryPatientInfo(string PatientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYAddDeposit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ZYAddDeposit(string HosNo, string Amt, string PayMode, string BankNo, string FlowNo, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYQueryAddBalanceRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ZYQueryAddBalanceRecord(string HosNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYQueryPatientInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ZYQueryPatientInfo(string HosNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZYQueryFeeDetailRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ZYQueryFeeDetailRecord(string HosNo, string BeginDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Checking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Checking(string Date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChisWebServiceSoapChannel : HisWebServiceTest.HisWebService.ChisWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChisWebServiceSoapClient : System.ServiceModel.ClientBase<HisWebServiceTest.HisWebService.ChisWebServiceSoap>, HisWebServiceTest.HisWebService.ChisWebServiceSoap {
        
        public ChisWebServiceSoapClient() {
        }
        
        public ChisWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChisWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChisWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChisWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string QueryPayType() {
            return base.Channel.QueryPayType();
        }
        
        public string CreateCardAddPosit(string CardNo, string PatientName, string Sex, string Birthday, string IDCardNo, string Nation, string Address, string Tel, string FlowNo, string Pwd, string Amt, string PayMode, string UserID) {
            return base.Channel.CreateCardAddPosit(CardNo, PatientName, Sex, Birthday, IDCardNo, Nation, Address, Tel, FlowNo, Pwd, Amt, PayMode, UserID);
        }
        
        public string AddDeposit(string PatientID, string Amt, string PayMode, string BankNo, string FlowNo, string UserID) {
            return base.Channel.AddDeposit(PatientID, Amt, PayMode, BankNo, FlowNo, UserID);
        }
        
        public string QueryPatientID(string CardNo) {
            return base.Channel.QueryPatientID(CardNo);
        }
        
        public string QueryBalanceRecord(string PatientID) {
            return base.Channel.QueryBalanceRecord(PatientID);
        }
        
        public string QueryFeeDetailRecord(string PatientID, string BeginDate, string EndDate) {
            return base.Channel.QueryFeeDetailRecord(PatientID, BeginDate, EndDate);
        }
        
        public string QueryPatientInfo(string PatientID) {
            return base.Channel.QueryPatientInfo(PatientID);
        }
        
        public string ZYAddDeposit(string HosNo, string Amt, string PayMode, string BankNo, string FlowNo, string UserID) {
            return base.Channel.ZYAddDeposit(HosNo, Amt, PayMode, BankNo, FlowNo, UserID);
        }
        
        public string ZYQueryAddBalanceRecord(string HosNo) {
            return base.Channel.ZYQueryAddBalanceRecord(HosNo);
        }
        
        public string ZYQueryPatientInfo(string HosNo) {
            return base.Channel.ZYQueryPatientInfo(HosNo);
        }
        
        public string ZYQueryFeeDetailRecord(string HosNo, string BeginDate, string EndDate) {
            return base.Channel.ZYQueryFeeDetailRecord(HosNo, BeginDate, EndDate);
        }
        
        public string Checking(string Date) {
            return base.Channel.Checking(Date);
        }
    }
}
